---
- hosts: linux
  gather_facts: false

  vars:
   ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

  tasks:
   - name: Install nginx
     package:
      name:
       - nginx
      state: latest
     become: yes # noqa 403

   - name: copy index.html
     copy:
       src: index.html
       dest: /usr/share/nginx/html/index.html
     become: yes  # noqa 208

   - name: start nginx service
     service:
        name: nginx
        state: started
     become: yes
