- hosts: all
  vars_prompt:
    - name: user
      prompt: "Enter ssh user"
    - name: password
      prompt: "Enter password for ssh user"
  vars:
    ansible_user: "{{user}}"
    ansible_password: "{{password}}"
    ansible_winrm_server_cert_validation: ignore
    ansible_connection: winrm
  tasks:
  - name: run win ping
    win_ping:
    