name: Ansible Lint
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: action/checkout@v2

    - name: Lint ansible Playbooks
      uses: ansible/ansible-lint-action@master
      with:
       targets: ""