name: Ansible Lint
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v2

    - name: Lint ansible Playbooks
      uses: ansible/ansible-lint-action@master
      with:
       targets: ""
       override-deps: |
          ansible==2.9
          ansible-lint==4.2.0